package no.imr.barentswatch.pdf;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.HashMap;

import javax.imageio.ImageIO;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class PrintHelper {

	@RequestMapping("/printhelper")
	public ModelAndView handleRequest(HttpServletRequest request, HttpServletResponse response) throws Exception {
        System.out.println("printhelper");
		/*BufferedImage legend_img = ImageIO.read(new URL(legend_url));
        BufferedImage theMapImage = new BufferedImage(1280, 776, BufferedImage.TYPE_4BYTE_ABGR);
        Graphics2D g2d = (Graphics2D) theMapImage.getGraphics();
        g2d.drawImage(base_layer, 0, 0, null);
        g2d.drawImage(second, 0, 0, null);*/

        response.setContentType("application/pdf");
        response.setHeader("Content-Transfer-Encoding", "Binary");
        response.setHeader("Content-Disposition", "attachment; filename=\"plot.pdf\";");
        String GeneralText = "This report have been generated by the FishExChange database,";
        

        BufferedImage theIMRLogoImage = null;
        theIMRLogoImage = ImageIO.read(request.getSession().getServletContext().getResourceAsStream("images/HIhoved_bla_bm-eng_CMYK2.jpg"));
        BufferedImage theSSFLogoImage = ImageIO.read(request.getSession().getServletContext().getResourceAsStream("images/SSF_logo.jpg"));
        HashMap<String, Object> parameterHash = new HashMap<String, Object>();
        parameterHash.put("ABOUT_FISHEXCHANGE", GeneralText);
        parameterHash.put("META_TEXT_PARAMETER", "tmp_metadata");
        parameterHash.put("IMR_Logo_Image", theIMRLogoImage);
        parameterHash.put("SSF_Logo_Image", theSSFLogoImage);
        //parameterHash.put("Map_Image", theMapImage);
        //parameterHash.put("LEGEND_image", legend_img);

        InputStream inputfile = (InputStream) request.getSession().getServletContext().getResourceAsStream("images/barentswatchTemplate.jrxml");
        JasperReport reportWithParameter = JasperCompileManager.compileReport(inputfile);
        JasperPrint printWithParameter = JasperFillManager.fillReport(reportWithParameter, parameterHash, new JREmptyDataSource());
        OutputStream outputfile = response.getOutputStream();
        JasperExportManager.exportReportToPdfStream(printWithParameter, outputfile);
        outputfile.close();
		
        System.out.println("ferdig printhelper "+outputfile);
        ModelAndView mav = new ModelAndView("choises");
		return mav;
        //return null;

	}
}
